### ISSUE TITLE
[FEAT] 메인뷰 서버 연결

### ISSUE THREAD

**Issue by sub101** [TEAM-Peenector/Peenector-aos#10]
## 💡 Issue
서버 연결

## 📝 todo
- [ ] request 객체 설계
- [ ] retrofit interface 설계 
- [ ] retrofit interface 실제 구현체(객체) 만들기
- [ ] callbak 등록해 통신 요청
